{
 "title": "Zabbix - Server Monitoring",
 "tags": [
  "monitoring",
  "zabbix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Zabbix Server Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": {
      "filter": "Zabbix server: Availability of Zabbix server"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Utilization (Zabbix)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Usage (Zabbix)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}